name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14]  # Specify the Node.js version you need

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies and build
        run: |
          cd server
          npm install
          cd ../
          cd client
          npm install
          npm run build

      - name: Copy files to /var/www/html
        run: |
          sudo cp -r client/build/* /var/www/html/
